# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
run:
  build-tags:
    - integration_test
    - unit_test
    - e2e_test
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - gocognit
    - gocritic
    - gocyclo
    - goheader
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    # Disabled until https://github.com/dominikh/go-tools/issues/1616 is fixed.
    # - unused
    - wastedassign
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocognit:
      min-complexity: 40
    gocritic:
      disabled-checks:
        - singleCaseSwitch
      enabled-tags:
        - opinionated
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: strict
    rules:
      - linters:
          - revive
        text: "error-strings: error strings should not be capitalized or end with punctuation or a newline"
issues:
  # Value 0 means show all.
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - golines
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nobl9/govy
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120
  exclusions:
    generated: strict
