// Code generated by "stringer -type=templateKey"; DO NOT EDIT.

package messagetemplates

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LengthTemplate-1]
	_ = x[MinLengthTemplate-2]
	_ = x[MaxLengthTemplate-3]
	_ = x[EQTemplate-4]
	_ = x[NEQTemplate-5]
	_ = x[GTTemplate-6]
	_ = x[GTETemplate-7]
	_ = x[LTTemplate-8]
	_ = x[LTETemplate-9]
	_ = x[EqualPropertiesTemplate-10]
	_ = x[GTPropertiesTemplate-11]
	_ = x[GTEPropertiesTemplate-12]
	_ = x[LTPropertiesTemplate-13]
	_ = x[LTEPropertiesTemplate-14]
	_ = x[GTComparablePropertiesTemplate-15]
	_ = x[GTEComparablePropertiesTemplate-16]
	_ = x[LTComparablePropertiesTemplate-17]
	_ = x[LTEComparablePropertiesTemplate-18]
	_ = x[DurationPrecisionTemplate-19]
	_ = x[ForbiddenTemplate-20]
	_ = x[OneOfTemplate-21]
	_ = x[NotOneOfTemplate-22]
	_ = x[OneOfPropertiesTemplate-23]
	_ = x[MutuallyExclusiveTemplate-24]
	_ = x[MutuallyDependentTemplate-25]
	_ = x[RequiredTemplate-26]
	_ = x[StringNonEmptyTemplate-27]
	_ = x[StringMatchRegexpTemplate-28]
	_ = x[StringDenyRegexpTemplate-29]
	_ = x[StringMD5Template-30]
	_ = x[StringSHA256Template-31]
	_ = x[StringSHA384Template-32]
	_ = x[StringSHA512Template-33]
	_ = x[StringEmailTemplate-34]
	_ = x[StringE164Template-35]
	_ = x[StringMACTemplate-36]
	_ = x[StringIPTemplate-37]
	_ = x[StringIPv4Template-38]
	_ = x[StringIPv6Template-39]
	_ = x[StringCIDRTemplate-40]
	_ = x[StringCIDRv4Template-41]
	_ = x[StringCIDRv6Template-42]
	_ = x[StringEINTemplate-43]
	_ = x[StringSSNTemplate-44]
	_ = x[StringJSONTemplate-45]
	_ = x[StringSemverTemplate-46]
	_ = x[StringCVETemplate-47]
	_ = x[StringJWTTemplate-48]
	_ = x[StringContainsTemplate-49]
	_ = x[StringExcludesTemplate-50]
	_ = x[StringStartsWithTemplate-51]
	_ = x[StringEndsWithTemplate-52]
	_ = x[StringTitleTemplate-53]
	_ = x[StringGitRefTemplate-54]
	_ = x[StringFileSystemPathTemplate-55]
	_ = x[StringFilePathTemplate-56]
	_ = x[StringDirPathTemplate-57]
	_ = x[StringMatchFileSystemPathTemplate-58]
	_ = x[StringRegexpTemplate-59]
	_ = x[StringCrontabTemplate-60]
	_ = x[StringDateTimeTemplate-61]
	_ = x[StringTimeZoneTemplate-62]
	_ = x[StringKubernetesQualifiedNameTemplate-63]
	_ = x[StringMongoDBObjectIDTemplate-64]
	_ = x[URLTemplate-65]
	_ = x[SliceUniqueTemplate-66]
	_ = x[UniquePropertiesTemplate-67]
}

const _templateKey_name = "LengthTemplateMinLengthTemplateMaxLengthTemplateEQTemplateNEQTemplateGTTemplateGTETemplateLTTemplateLTETemplateEqualPropertiesTemplateGTPropertiesTemplateGTEPropertiesTemplateLTPropertiesTemplateLTEPropertiesTemplateGTComparablePropertiesTemplateGTEComparablePropertiesTemplateLTComparablePropertiesTemplateLTEComparablePropertiesTemplateDurationPrecisionTemplateForbiddenTemplateOneOfTemplateNotOneOfTemplateOneOfPropertiesTemplateMutuallyExclusiveTemplateMutuallyDependentTemplateRequiredTemplateStringNonEmptyTemplateStringMatchRegexpTemplateStringDenyRegexpTemplateStringMD5TemplateStringSHA256TemplateStringSHA384TemplateStringSHA512TemplateStringEmailTemplateStringE164TemplateStringMACTemplateStringIPTemplateStringIPv4TemplateStringIPv6TemplateStringCIDRTemplateStringCIDRv4TemplateStringCIDRv6TemplateStringEINTemplateStringSSNTemplateStringJSONTemplateStringSemverTemplateStringCVETemplateStringJWTTemplateStringContainsTemplateStringExcludesTemplateStringStartsWithTemplateStringEndsWithTemplateStringTitleTemplateStringGitRefTemplateStringFileSystemPathTemplateStringFilePathTemplateStringDirPathTemplateStringMatchFileSystemPathTemplateStringRegexpTemplateStringCrontabTemplateStringDateTimeTemplateStringTimeZoneTemplateStringKubernetesQualifiedNameTemplateStringMongoDBObjectIDTemplateURLTemplateSliceUniqueTemplateUniquePropertiesTemplate"

var _templateKey_index = [...]uint16{0, 14, 31, 48, 58, 69, 79, 90, 100, 111, 134, 154, 175, 195, 216, 246, 277, 307, 338, 363, 380, 393, 409, 432, 457, 482, 498, 520, 545, 569, 586, 606, 626, 646, 665, 683, 700, 716, 734, 752, 770, 790, 810, 827, 844, 862, 882, 899, 916, 938, 960, 984, 1006, 1025, 1045, 1073, 1095, 1116, 1149, 1169, 1190, 1212, 1234, 1271, 1300, 1311, 1330, 1354}

func (i templateKey) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_templateKey_index)-1 {
		return "templateKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _templateKey_name[_templateKey_index[idx]:_templateKey_index[idx+1]]
}
