// Code generated by "stringer -type=templateKey"; DO NOT EDIT.

package messagetemplates

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LengthTemplate-1]
	_ = x[MinLengthTemplate-2]
	_ = x[MaxLengthTemplate-3]
	_ = x[EQTemplate-4]
	_ = x[NEQTemplate-5]
	_ = x[GTTemplate-6]
	_ = x[GTETemplate-7]
	_ = x[LTTemplate-8]
	_ = x[LTETemplate-9]
	_ = x[EqualPropertiesTemplate-10]
	_ = x[GTPropertiesTemplate-11]
	_ = x[GTEPropertiesTemplate-12]
	_ = x[LTPropertiesTemplate-13]
	_ = x[LTEPropertiesTemplate-14]
	_ = x[GTComparablePropertiesTemplate-15]
	_ = x[GTEComparablePropertiesTemplate-16]
	_ = x[LTComparablePropertiesTemplate-17]
	_ = x[LTEComparablePropertiesTemplate-18]
	_ = x[DurationPrecisionTemplate-19]
	_ = x[ForbiddenTemplate-20]
	_ = x[OneOfTemplate-21]
	_ = x[NotOneOfTemplate-22]
	_ = x[OneOfPropertiesTemplate-23]
	_ = x[MutuallyExclusiveTemplate-24]
	_ = x[MutuallyDependentTemplate-25]
	_ = x[RequiredTemplate-26]
	_ = x[StringNonEmptyTemplate-27]
	_ = x[StringMatchRegexpTemplate-28]
	_ = x[StringDenyRegexpTemplate-29]
	_ = x[StringEmailTemplate-30]
	_ = x[StringE164Template-31]
	_ = x[StringMACTemplate-32]
	_ = x[StringIPTemplate-33]
	_ = x[StringIPv4Template-34]
	_ = x[StringIPv6Template-35]
	_ = x[StringCIDRTemplate-36]
	_ = x[StringCIDRv4Template-37]
	_ = x[StringCIDRv6Template-38]
	_ = x[StringJSONTemplate-39]
	_ = x[StringSemverTemplate-40]
	_ = x[StringCVETemplate-41]
	_ = x[StringContainsTemplate-42]
	_ = x[StringExcludesTemplate-43]
	_ = x[StringStartsWithTemplate-44]
	_ = x[StringEndsWithTemplate-45]
	_ = x[StringTitleTemplate-46]
	_ = x[StringGitRefTemplate-47]
	_ = x[StringFileSystemPathTemplate-48]
	_ = x[StringFilePathTemplate-49]
	_ = x[StringDirPathTemplate-50]
	_ = x[StringMatchFileSystemPathTemplate-51]
	_ = x[StringRegexpTemplate-52]
	_ = x[StringCrontabTemplate-53]
	_ = x[StringDateTimeTemplate-54]
	_ = x[StringTimeZoneTemplate-55]
	_ = x[StringKubernetesQualifiedNameTemplate-56]
	_ = x[StringBTCAddressTemplate-57]
	_ = x[StringBTCBech32AddressTemplate-58]
	_ = x[StringETHAddressTemplate-59]
	_ = x[URLTemplate-60]
	_ = x[SliceUniqueTemplate-61]
	_ = x[UniquePropertiesTemplate-62]
}

const _templateKey_name = "LengthTemplateMinLengthTemplateMaxLengthTemplateEQTemplateNEQTemplateGTTemplateGTETemplateLTTemplateLTETemplateEqualPropertiesTemplateGTPropertiesTemplateGTEPropertiesTemplateLTPropertiesTemplateLTEPropertiesTemplateGTComparablePropertiesTemplateGTEComparablePropertiesTemplateLTComparablePropertiesTemplateLTEComparablePropertiesTemplateDurationPrecisionTemplateForbiddenTemplateOneOfTemplateNotOneOfTemplateOneOfPropertiesTemplateMutuallyExclusiveTemplateMutuallyDependentTemplateRequiredTemplateStringNonEmptyTemplateStringMatchRegexpTemplateStringDenyRegexpTemplateStringEmailTemplateStringE164TemplateStringMACTemplateStringIPTemplateStringIPv4TemplateStringIPv6TemplateStringCIDRTemplateStringCIDRv4TemplateStringCIDRv6TemplateStringJSONTemplateStringSemverTemplateStringCVETemplateStringContainsTemplateStringExcludesTemplateStringStartsWithTemplateStringEndsWithTemplateStringTitleTemplateStringGitRefTemplateStringFileSystemPathTemplateStringFilePathTemplateStringDirPathTemplateStringMatchFileSystemPathTemplateStringRegexpTemplateStringCrontabTemplateStringDateTimeTemplateStringTimeZoneTemplateStringKubernetesQualifiedNameTemplateStringBTCAddressTemplateStringBTCBech32AddressTemplateStringETHAddressTemplateURLTemplateSliceUniqueTemplateUniquePropertiesTemplate"

var _templateKey_index = [...]uint16{0, 14, 31, 48, 58, 69, 79, 90, 100, 111, 134, 154, 175, 195, 216, 246, 277, 307, 338, 363, 380, 393, 409, 432, 457, 482, 498, 520, 545, 569, 588, 606, 623, 639, 657, 675, 693, 713, 733, 751, 771, 788, 810, 832, 856, 878, 897, 917, 945, 967, 988, 1021, 1041, 1062, 1084, 1106, 1143, 1167, 1197, 1221, 1232, 1251, 1275}

func (i templateKey) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_templateKey_index)-1 {
		return "templateKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _templateKey_name[_templateKey_index[idx]:_templateKey_index[idx+1]]
}
