name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.11.0
        with:
          enable-cache: true
      - name: Run unit tests
        run: devbox run -- make test
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GO_COVERAGE_TOKEN }}
        if: github.event_name == 'push'
        continue-on-error: true
