name: Tests
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.13.0
        with:
          enable-cache: true
          devbox-version: ${{ vars.DEVBOX_VERSION }}
      - name: Run unit tests
        run: devbox run -- make test
      - name: Run benchmark
        run: make test/benchmark | tee benchmark.txt
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Govy Go Benchmark
          tool: 'go'
          alert-threshold: '150%'
          output-file-path: benchmark.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: false
          # Commit comment.
          comment-on-alert: true
          alert-comment-cc-users: '@nieomylnieja'
          github-token: ${{ secrets.GO_BENCHMARK_TOKEN }}
