name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  deployments: write
  contents: write
  pull-requests: write
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.11.0
        with:
          enable-cache: true
      - name: Run unit tests
        run: devbox run -- make test
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GO_COVERAGE_TOKEN }}
        if: github.event_name == 'push'
        continue-on-error: true
      - name: Run benchmark
        run: make test/benchmark | tee benchmark.txt
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Govy Go Benchmark
          tool: 'go'
          output-file-path: benchmark.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: false
          # Commit comment.
          comment-on-alert: true
          alert-comment-cc-users: '@nieomylnieja'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # We update GitHub pages only on on 'push' events below.
          auto-push: false
      - name: Push benchmark result
        if: github.event_name == 'push'
        run: git push 'https://nobl9:${{ secrets.GITHUB_TOKEN }}@github.com/nobl9/govy.git' gh-pages:gh-pages
