name: Vulnerabilities
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run at 8:00 AM every weekday.
    - cron:  '0 8 * * 1-5'
jobs:
  scan:
    name: Run Golang vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.14.0
        with:
          enable-cache: true
          devbox-version: ${{ vars.DEVBOX_VERSION }}
      - name: Run vulnerability check
        run: devbox run -- make check/vulns
